# Simple workflow for deploying static content to GitHub Pages
name: Ping Google About Updated Sitemap

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - sitemap.xml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
  ping:
    name: Ping Google
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP GET request
        run: 'curl http://www.google.com/ping?sitemap=https://babyno.top/sitemap.xml'
